dist: trusty

os:
  - osx
  - linux

language: node_js

node_js:
  - 4
  - 6
  - 8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi

script:
  - yarn
  - yarn prebuild
  - yarn upload
