image: Visual Studio 2017
platform:
  - x64

install:
  - ps: Install-Product node 8 x64
  - yarn

test_script:
  - ps: Remove-Item .\prebuilds -Force -Recurse
  - yarn prebuild
  - yarn prebuild-ia32
  - yarn upload

build: off

branches:
  only:
    - master