environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"

image: Visual Studio 2017
platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn

test_script:
  - yarn prebuild
  - yarn upload

build: off
